// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCtJfrUeW8vz32VDW_2VUXb7n36_bXPdtE',
    appId: '1:872328902883:web:171c8639cc23966164edd6',
    messagingSenderId: '872328902883',
    projectId: 'devbilal-to-do-app',
    authDomain: 'devbilal-to-do-app.firebaseapp.com',
    storageBucket: 'devbilal-to-do-app.appspot.com',
    measurementId: 'G-EXS5H94JB4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA93K6N_LBkE09E7vt6-UML27VF3Chtwtw',
    appId: '1:872328902883:android:4ec1ef1c4b293ec864edd6',
    messagingSenderId: '872328902883',
    projectId: 'devbilal-to-do-app',
    storageBucket: 'devbilal-to-do-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDg9Hjp8gPawFZB4i6Nt1C0plqMTFFc_vo',
    appId: '1:872328902883:ios:2299d9820a44f46164edd6',
    messagingSenderId: '872328902883',
    projectId: 'devbilal-to-do-app',
    storageBucket: 'devbilal-to-do-app.appspot.com',
    iosClientId: '872328902883-ds25jd4t9mslausfbelrbqcrspn6j99b.apps.googleusercontent.com',
    iosBundleId: 'com.example.toDoApp',
  );
}
